name: Build libsamplerate for UWP

on:
  push:
    paths:
      - 'src/dep/libsamplerate/**'
  pull_request:
    paths:
      - 'src/dep/libsamplerate/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ../src/dep/libsamplerate -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_BUILD_TYPE=Release

    - name: Build libsamplerate
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libsamplerate-uwp
        path: |
          build/Release/*.lib
          build/Release/*.dll
