name: Build SDL2-UWP

on:
  workflow_dispatch:  # Manually triggerable

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download SDL2-UWP
        run: |
          curl -L https://github.com/izzy2lost/Flamenco-UWP/releases/download/2.30.1/SDL2-2.30.1.zip

      - name: Extract SDL2
        run: |
          7z x SDL2-2.30.1.zip

      - name: Build SDL2-UWP
        run: |
          cd SDL2-2.30.1/VisualC-WinRT
          msbuild SDL-UWP.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload SDL2-UWP Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SDL2-UWP
          path: SDL2-2.30.1/VisualC-WinRT/x64/Release/
