name: Make Depends

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag Name"
        required: true
        default: "v1.0.0"
      package_name:
        description: "Package Name"
        required: true
        default: "ReleaseUWP"

jobs:
  build:
    runs-on: windows-latest

    env:
      SolutionPath: duckstation.sln
      Platform: x64
      Configuration: ReleaseUWP
      BuildMode: SideLoadOnly
      AppxBundle: Never
      ProjectPath: src/duckstation-uwp/duckstation-uwp.vcxproj
      ProjectDirectory: .\src\duckstation-uwp\
      PackageOutputRootDir: C:\AppPackage
      PackageOutputDir: ReleaseUWP

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install MSYS2 and pkg-config
        uses: msys2/setup-msys2@v2
        with:
          install: pkgconf
          path-type: minimal

      - name: Setup MinGW64 Shell
        run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH

      - name: Verify pkg-config
        run: pkg-config --version
        shell: msys2 {0}

      - name: Build X64 Dependencies
        env:
          DEBUG: 0
        run: scripts/build-dependencies-windows-x64.bat

      - name: Create Dependencies Archive
        shell: cmd
        run: |
          cd \duckstation-uwp\dep\msvc
          "C:\Program Files\7-Zip\7z.exe" a "%GITHUB_WORKSPACE%\deps-x64.7z" .\deps-x64

      - name: Upload Dependencies Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deps-x64
          path: deps-x64.7z
          if-no-files-found: error
