name: Build util

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      SolutionPath: src/util/util.vcxproj
      Platform: x64
      Configuration: Release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup MinGW
        run: |
          choco install mingw -y
        shell: pwsh

      - name: Add MinGW to PATH
        run: |
          echo "C:\tools\mingw64\bin" >> $GITHUB_PATH
        shell: pwsh

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore NuGet Packages
        run: |
          nuget restore $env:SolutionPath
        shell: pwsh

      - name: Get CMake
        uses: lukka/get-cmake@v3.31.5

      - name: Build zlib Library
        run: |
          cmake -G "MinGW Makefiles" -S dep/zlib -B build/zlib
          cmake --build build/zlib
        shell: pwsh

      - name: Build zstd Library
        run: |
          cmake -G "MinGW Makefiles" -S dep/zstd -B build/zstd
          cmake --build build/zstd
        shell: pwsh

      - name: Build util Project
        run: |
          cmake -G "MinGW Makefiles" -S src/util -B build/util
          cmake --build build/util
        shell: pwsh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: util Build
          path: build/util/**
