name: Build UWP with vcpkg

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install vcpkg (pinned to a specific commit)
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          git checkout 2024.02.14  # Example: Use a stable vcpkg version
          .\bootstrap-vcpkg.bat

      - name: Install dependencies via vcpkg (specific versions)
        run: |
          C:\vcpkg\vcpkg install sdl2:x64-uwp@2.30.1
          C:\vcpkg\vcpkg install qtbase:x64-uwp@6.6.2
          C:\vcpkg\vcpkg install qtsvg:x64-uwp@6.6.2
          C:\vcpkg\vcpkg install qttools:x64-uwp@6.6.2
          C:\vcpkg\vcpkg install qtimageformats:x64-uwp@6.6.2
          C:\vcpkg\vcpkg install qttranslations:x64-uwp@6.6.2
          C:\vcpkg\vcpkg integrate install

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX="deps-x64"

      - name: Build and Install
        run: |
          cmake --build build --parallel
          cmake --install build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uwp-build
          path: deps-x64/